apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ky36wixeq-python 
  janus-idp.io/tekton: ky36wixeq-python
  backstage.io/kubernetes-id: ky36wixeq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ky36wixeq-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  