apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ky36wixeq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ky36wixeq-python 
  name: ky36wixeq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ky36wixeq-python 
